services:

  db:
    image: postgres:15
    container_name: postgres-unidb
    env_file: .env.docker
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: redis-uniask
    ports:
      - "6379:6379"
    networks:
      - app_network

  web:
    build: .
    container_name: gunicorn-web
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn -c gunicorn.conf.py application.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env.docker
    networks:
      - app_network

  wsgi_simple:
    build: .
    container_name: wsgi-simple
    command: gunicorn wsgi_simple:application --bind 0.0.0.0:8081 --workers 2
    volumes:
      - .:/app
    ports:
      - "8082:8081"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx-uniask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

  celery:
    build: .
    container_name: celery-worker
    command: celery -A application worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file: .env.docker
    networks:
      - app_network

  celerybeat:
    build: .
    container_name: celery-beat
    command: celery -A application beat -l info -S redbeat.RedBeatScheduler
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file: .env.docker
    networks:
      - app_network

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    command: centrifugo -c /centrifugo/config.json
    volumes:
      - ./centrifugo.json:/centrifugo/config.json
    ports:
      - "8001:8000"
    environment:
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=${CENTRIFUGO_TOKEN_SECRET}
      - CENTRIFUGO_API_KEY=${CENTRIFUGO_API_KEY}
      - CENTRIFUGO_ADMIN=true
      - CENTRIFUGO_ADMIN_PASSWORD=${CENTRIFUGO_ADMIN_PASSWORD}
      - CENTRIFUGO_ADMIN_SECRET=${CENTRIFUGO_ADMIN_SECRET}
    networks:
      - app_network

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"  # веб-интерфейс
      - "1025:1025"  # SMTP
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
