services:
  db:
    image: postgres:15
    container_name: postgres-unidb-compose
    environment:
      POSTGRES_DB: unidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - django_network

  web:
    build: .
    container_name: django-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=unidb
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network: